name: Security Scan

on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sudo sh -s -- -b /usr/local/bin
          trivy --version

      - name: Install Gitleaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -O gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
          gitleaks --version

      - name: Run security scans
        env:
          CI: "true"
        run: |
          chmod +x ./automate_cicd_scan.sh
          ./automate_cicd_scan.sh

      - name: Upload JSON reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            trivy_output.json
            gitleaks_output.json
          if-no-files-found: warn
